[package]
name = "ao3-tui"
version = "0.1.0"
description = "A terminal reader for Archive of Our Own."
authors = ["reihera <nightshadegamer200yt@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
scraper = "0.23.1"
