[package]
name = "ao3-tui"
version = "0.1.0"
edition = "2024"
authors = ["reihera"]
description = "a tui reader for Archive of Our Own"
homepage = "https://github.com/reihera/ao3-tui"

[dependencies]
crossterm = "0.29.0"
tui = "0.19.0"
